Screen:

    MDRaisedButton
        text : "Light Button"
        pos_hint : {"center_x":0.5, "center_y" :0.8}
        md_bg_color :app.theme_cls.primary_light



    MDRaisedButton
        text : "Red Button"
        pos_hint : {"center_x":0.5, "center_y" :0.5}
        md_bg_color :app.theme_cls.accent_dark

    MDRaisedButton
        text : "First Button"
        pos_hint : {"center_x":0.5, "center_y" :0.3}
        md_bg_color :app.theme_cls.primary_dark